export const quotes = {
  happy: {
    quotes: [
      'Stay positive!',
      'Keep smiling!',
      'Smile, it’s contagious!',
      'Every day is a new beginning!',
      'Joy is a choice—choose it today!',
      'Happiness is an inside job.',
      'Life is beautiful, enjoy every moment.',
      'Embrace the glorious mess that you are.',
      'The best is yet to come.',
      'Count your blessings.',
      'Choose to be optimistic.',
      'Believe in the power of positivity.',
      'Happiness is a journey, not a destination.',
      'Let your light shine.',
      'Be the reason someone smiles today.',
      'Laughter is the best medicine.',
      'Find joy in the little things.',
      'Keep your face always toward the sunshine.',
      'Positive mind. Positive vibes. Positive life.',
      'Radiate positivity.',
    ],
    reminders: [
      'Drink water',
      'Take a break',
      'Take a deep breath',
      'Celebrate small victories',
      'Keep moving forward',
      'Practice gratitude',
      'Stay active',
      'Eat something healthy',
      'Smile at a stranger',
      'Call a friend',
      'Enjoy the moment',
      'Do something fun',
      'Stretch your legs',
      'Dance to your favorite song',
      'Remember to laugh',
      'Take time for self-care',
      'Reflect on the good things',
      'Write down three positive thoughts',
      'Spend time outdoors',
      'Cherish every moment',
    ],
    funFacts: [
      'Honey never spoils.',
      'Bananas are berries.',
      'Laughter boosts your immune system.',
      'Dolphins sleep with one eye open.',
      'Sunflowers track the sun throughout the day.',
      'A group of flamingos is called a flamboyance.',
      'Koalas sleep up to 22 hours a day.',
      'Elephants can’t jump.',
      'Some turtles can breathe through their butts.',
      'A snail can sleep for three years.',
      'There are more stars in the universe than grains of sand on Earth.',
      'Cows have best friends.',
      'Butterflies can see ultraviolet light.',
      'A day on Venus is longer than a year on Venus.',
      'Octopuses have blue blood.',
      'Hot water freezes faster than cold water (Mpemba effect).',
      'A group of kittens is called a kindle.',
      'Avocados are berries.',
      'Peanuts are not nuts; they are legumes.',
      'An eagle can see four to five times better than a human.',
    ],
  },
  sad: {
    quotes: [
      "It's okay to feel sad.",
      'Take your time.',
      'This too shall pass.',
      'Every storm runs out of rain.',
      'Tears are the silent language of grief.',
      'Sometimes, sadness is necessary.',
      'Even the darkest night will end and the sun will rise.',
      'Let your tears water your soul.',
      'Healing takes time.',
      'Embrace your emotions.',
      'Your feelings are valid.',
      "It's alright to not be okay.",
      'Sadness is a part of life.',
      'Every tear is a step toward healing.',
      'You are stronger than you think.',
      'Allow yourself to feel, then let it go.',
      'After the rain comes the rainbow.',
      'Sometimes you need to cry to heal.',
      'Embrace your inner strength.',
      'There is beauty in the struggle.',
    ],
    reminders: [
      'Talk to a friend',
      'Take a walk',
      'Call someone who cares',
      'Write down your thoughts',
      'Remember to breathe',
      'Give yourself time',
      'Allow yourself to rest',
      'Seek comfort in solitude',
      'Reach out for help',
      'Be kind to yourself',
      'Listen to soothing music',
      'Watch your favorite movie',
      'Do something that heals your heart',
      'Practice self-compassion',
      'Reflect on positive memories',
      'Treat yourself gently',
      'Take a mindful pause',
      'Spend time with loved ones',
      'Journal your feelings',
      'Believe that better days will come',
    ],
    funFacts: [
      'Octopuses have three hearts.',
      'Butterflies taste with their feet.',
      'Crows are incredibly smart.',
      'Koalas sleep up to 22 hours a day.',
      'Sea otters hold hands while sleeping.',
      'Some metals can be liquid near room temperature.',
      'A broken clock is right twice a day.',
      'Rainbows can occur at night (moonbows).',
      'The heart of a blue whale is as big as a small car.',
      'There are more trees on Earth than stars in the Milky Way.',
      'The human brain can hold 2.5 petabytes of information.',
      'Some frogs can freeze without dying.',
      'Sloths can hold their breath for 40 minutes.',
      'A bolt of lightning contains enough energy to toast 100,000 slices of bread.',
      'The Eiffel Tower can be 15 cm taller during the summer.',
      'A day on Venus is longer than a year on Venus.',
      'Some cats are allergic to humans.',
      'There are more fake flamingos in the world than real ones.',
      'The smell of rain is caused by a bacteria called actinomycetes.',
      'A single strand of spaghetti is called a spaghetto.',
    ],
  },
  calm: {
    quotes: [
      'Stay calm!',
      'Relax and take a deep breath.',
      'Find peace within.',
      'Tranquility is a state of mind.',
      'Let serenity guide you.',
      'Peace begins with a smile.',
      'Keep calm and carry on.',
      'Breathe in, breathe out, relax.',
      'Calm is a superpower.',
      'Inhale peace, exhale stress.',
      'Serenity is not freedom from the storm, but peace amid the storm.',
      'Silence is sometimes the best answer.',
      'Quiet the mind and the soul will speak.',
      'Embrace the stillness.',
      'Peace is within your reach.',
      'Let go of what you cannot control.',
      'Allow yourself to slow down.',
      'Your calm mind is the ultimate weapon against your challenges.',
      'Find beauty in simplicity.',
      'Rest, relax, rejuvenate.',
    ],
    reminders: [
      'Stretch your body.',
      'Meditate for 5 minutes.',
      'Enjoy a quiet moment.',
      'Find a peaceful corner.',
      'Listen to calming music.',
      'Take a deep breath.',
      'Slow down and relax.',
      'Close your eyes and unwind.',
      'Embrace the moment.',
      'Reflect on your blessings.',
      'Take a short walk.',
      'Focus on your breath.',
      'Do some gentle yoga.',
      'Sit in silence for a moment.',
      'Let go of tension.',
      'Drink a cup of herbal tea.',
      'Write down what you’re grateful for.',
      'Watch the sunset.',
      'Practice mindfulness.',
      'Allow yourself a moment of peace.',
    ],
    funFacts: [
      'Polar bears are left-handed.',
      'Oysters can fly.',
      'Bamboo can grow up to 91 cm in a day.',
      "A hummingbird's heart beats over 1,200 times per minute.",
      'Clouds can weigh over a million pounds!',
      'Some sea cucumbers can eject their internal organs to escape predators.',
      'The average person walks the equivalent of three times around the world in a lifetime.',
      'A group of flamingos is called a flamboyance.',
      'The deepest part of the ocean is over 36,000 feet deep.',
      'Ants never sleep.',
      'The tongue is the strongest muscle in the human body relative to its size.',
      'A bolt of lightning is five times hotter than the surface of the sun.',
      'Some crabs can walk sideways at 10 mph.',
      'The human brain generates enough electricity to power a light bulb.',
      'A snail can sleep for three years.',
      'The world’s oldest known creature was a 507-year-old clam.',
      'The Eiffel Tower can be 15 cm taller during the summer.',
      'A day on Venus is longer than a year on Venus.',
      'Some penguins propose to their mates with a pebble.',
      'The average cumulus cloud weighs about 1.1 million pounds!',
    ],
  },
};
